### ISSUE TITLE
TypeError: super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by xmuszq** [nanopony/keras-convautoencoder#2] opened 2016-03-10 07:11 UTC
Hi nano,

Thank you for sharing your excellent codes. 
I try to implement them (the autoencoder_layers.py) in spyder, I got following error. Can you help me check how to resolve it?

ipdb> Traceback (most recent call last):

  File "<ipython-input-28-78181ca4661a>", line 1, in <module>
    debugfile('C:/RESEARCH/Machine Learning/cell segmentation/codes/keras-convautoencoder-master/conv_autoencoder.py', wdir='C:/RESEARCH/Machine Learning/cell segmentation/codes/keras-convautoencoder-master')

  File "C:\Users\zhenqiang su\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 719, in debugfile
    debugger.run("runfile(%r, args=%r, wdir=%r)" % (filename, args, wdir))

  File "C:\Users\zhenqiang su\Anaconda2\lib\bdb.py", line 400, in run
    exec cmd in globals, locals

  File "<string>", line 1, in <module>

  File "C:\Users\zhenqiang su\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "C:\Users\zhenqiang su\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "c:/research/machine learning/cell segmentation/codes/keras-convautoencoder-master/conv_autoencoder.py", line 50, in <module>
    model = build_model()

  File "c:/research/machine learning/cell segmentation/codes/keras-convautoencoder-master/conv_autoencoder.py", line 37, in build_model
    model.add(DependentDense(nb_filters \* 14 \* 14, d))

  File "autoencoder_layers.py", line 279, in **init**
    super().**init**(output_dim, **kwargs)

TypeError: super() takes at least 1 argument (0 given)

**Comment by nanopony** [comment] 2016-03-10 10:20
@xmuszq What version of python are you using? If it is Python2.x, you might be required to fix ancestor call, since shorthand super() was introduced in Python3

Closing as duplicate of #1

**Closed as completed by nanopony** 2016-03-10 10:20 UTC

**Comment by xmuszq** [comment] 2016-03-10 22:56
Yes. You are right, it's caused by python version mis-match. 
It can be fixed by adding the parameters, like the following post did:
http://stackoverflow.com/questions/10838596/python-class-super-variable
